"""Added spotify_id to User model

Revision ID: 5e5de586659c
Revises: 
Create Date: 2025-02-06 16:49:29.472229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5de586659c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spotify_id', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('access_token', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('refresh_token', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint("uq_user_spotify_id", ['spotify_id'])
        batch_op.drop_column('email')
        batch_op.drop_column('username')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_constraint("uq_user_spotify_id", type_='unique')
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')
        batch_op.drop_column('spotify_id')

    # ### end Alembic commands ###
