"""Added top artists, top tracks, and top genres to User model

Revision ID: a745633896da
Revises: fbe4706e17a2
Create Date: 2025-02-23 13:05:33.671257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a745633896da'
down_revision = 'fbe4706e17a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_artists', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('top_tracks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('top_genres', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('top_genres')
        batch_op.drop_column('top_tracks')
        batch_op.drop_column('top_artists')

    # ### end Alembic commands ###
